### ISSUE TITLE
Add "home" button on top of posts page

### ISSUE THREAD

**Issue by archit-p** [archit-p/archit-p.github.io#1]
Currently when you view any post, there is no way to go back to the home page. 

Add a button to the top which says "Home". Use the same style as the "About" nav bar on home page.

**Comment by marqueslu** [comment]
Can i take this one?

**Comment by archit-p** [comment]
@marqueslu sure! Please add a new file called nav.html to the-_includes folder

**Comment by BestDanelleEver** [comment]
im gonna work on this
